---
- name: Create file configuration kafka
  template:
    src: templates/server.properties.j2
    dest: /data/apps/kafka/config/server.properties
- name: Create kafka service
  template:
    src: templates/kafka.service.j2
    dest: /etc/systemd/system/kafka.service
- name: reload daemon
  systemd:
    daemon-reload: true
- name: restart service
  systemd:
    name: kafka
    state: restarted
    enabled: true