- name: Create user
  user:
    name: "{{ userapp }}"
    system: yes
- name: Create Directory container data and log
  file:
    path: /data/apps/kafka
    state: directory
- name: Download kafka
  shell: cd /home/ansible/ & wget https://downloads.apache.org/kafka/3.7.0/kafka_2.12-3.7.0.tgz
- name: Extract kafka
  unarchive:
    src: /home/ansible/kafka_2.12-3.7.0.tgz
    dest: /home/ansible/
    remote_src: true
- name: move kafka to folder kafka
  shell: rm -rf /home/ansible/kafka_2.12-3.7.0.tgz.* & rsync -a /home/ansible/kafka_2.12-3.7.0/* /data/apps/kafka/
- name: Create folder data zookeeper
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /data/apps/kafka/data/zookeeper
    - /data/apps/kafka/data/kafka
- name: Create id for zookeeper
  shell: echo {{ hostvars[inventory_hostname].id }} > "{{ zookeeper.data_dir }}/myid"
- name: Create file zookeeper.properties
  template:
    src: template/zookeeper/zookeeper.properties.j2
    dest: /data/apps/kafka/config/zookeeper.properties
- name: Grant permission run service
  file:
    path: /data/apps/kafka
    owner: "{{ userapp }}"
    group: "{{ userapp }}"
    recurse: true
- name: Create file zookeeper.service
  template:
    src: template/zookeeper/zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
- name: reload demon
  systemd:
    daemon_reload: yes
- name: start service
  systemd:
    name: zookeeper
    state: started
    enabled: true
    